spring:
  application:
    name: eureka
server:
  port: 8712
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.hostname}:${server.port}
    preferIpAddress: true
    ip-address: ${EUREKA_IP:${eureka.instance.hostname}}
  client:
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8712/eureka/
      defaultZone: http://${eureka.instance.hostname}:8711/eureka/,http://${eureka.instance.hostname}:8713/eureka/
    fetch-registry: true
    register-with-eureka: true
